#!/usr/bin/env python

import sc.drive_now.main
import sc.multicity.main
import sc.car2go.main


def main():
    sc.drive_now.main.scrap()
    sc.multicity.main.scrap()
    sc.car2go.main.scrap()


if __name__ == '__main__':
    main()
