#!/usr/bin/env python

'''
Usage:
    parse_all [-ir]

Options:
  -i    Include data from today.
  -r    Remove parsed and achieved data.
'''

import datetime
import docopt
import os
import shutil
import sc.drive_now.main
import sc.multicity.main
import sc.car2go.main
from sc.io import get_data_path_alldays, get_data_path


def main():
    exclude_today = False if args.get('-i', False) else True
    rm_parsed = args.get('-r', False)

    archive_path = get_data_path('raw_archive')
    for day in get_data_path_alldays('raw'):
        if not (exclude_today and day == datetime.date.today().isoformat()):
            try:
                sc.drive_now.main.parse(day)
                sc.multicity.main.parse(day)
                sc.car2go.main.parse(day)
            except:
                raise
            else:
                try:
                    archive_name = os.path.expanduser(
                        os.path.join(archive_path, day))
                    raw_path = get_data_path('raw', day)
                    shutil.make_archive(archive_name, 'gztar', raw_path)
                except:
                    raise
                else:
                    if rm_parsed:
                        shutil.rmtree(raw_path)


if __name__ == '__main__':
    args = docopt.docopt(__doc__)
    main()
